import { defineConfig } from "vitest/config";
import path from "node:path";

export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    exclude: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.mosaix/**",
      "apps/_template/**",
    ],
  },
  resolve: {
    alias: {
      "@mosaix/core": path.resolve(__dirname, "./packages/core/src/index.ts"),
      "@mosaix/theme": path.resolve(__dirname, "./packages/theme/src/index.ts"),
      "@mosaix/contracts": path.resolve(__dirname, "./packages/contracts/src/index.ts"),
      "@mosaix/schemas": path.resolve(__dirname, "./packages/schemas/src/index.ts"),
      "@mosaix/security": path.resolve(__dirname, "./packages/security/src/index.ts"),
      "@mosaix/types": path.resolve(__dirname, "./packages/types/src/index.ts"),
      "@mosaix/container": path.resolve(__dirname, "./packages/container/src/index.ts"),
      "@mosaix/http": path.resolve(__dirname, "./packages/http/src/index.ts"),
      "@mosaix/events": path.resolve(__dirname, "./packages/events/src/index.ts"),
      "@mosaix/foundation": path.resolve(__dirname, "./packages/foundation/src/index.ts"),
      "@mosaix/sdk": path.resolve(__dirname, "./packages/sdk/src/index.ts"),
      "@mosaix/control-plane": path.resolve(__dirname, "./packages/control-plane/src/index.ts"),
      "@mosaix/migrations": path.resolve(__dirname, "./packages/migrations/src/index.ts"),
      "@mosaix/orm": path.resolve(__dirname, "./packages/orm/src/index.ts"),
      "@mosaix/pipeline": path.resolve(__dirname, "./packages/pipeline/src/index.ts"),
      "@mosaix/plugin-engine": path.resolve(__dirname, "./packages/plugin-engine/src/index.ts"),
      "@mosaix/telemetry": path.resolve(__dirname, "./packages/telemetry/src/index.ts"),
      "@mosaix/ui-runtime": path.resolve(__dirname, "./packages/ui-runtime/src/index.ts"),
      "@mosaix/auth": path.resolve(__dirname, "./packages/auth/src/index.ts"),
      "@mosaix/cache": path.resolve(__dirname, "./packages/cache/src/index.ts"),
      "@mosaix/commands": path.resolve(__dirname, "./packages/commands/src/index.ts"),
      "@mosaix/config": path.resolve(__dirname, "./packages/config/src/index.ts"),
      "@mosaix/conformance": path.resolve(__dirname, "./packages/conformance/src/index.ts"),
      "@mosaix/database": path.resolve(__dirname, "./packages/database/src/index.ts"),
      "@mosaix/filesystem": path.resolve(__dirname, "./packages/filesystem/src/index.ts"),
      "@mosaix/gateway": path.resolve(__dirname, "./packages/gateway/src/index.ts"),
      "@mosaix/mcp": path.resolve(__dirname, "./packages/mcp/src/index.ts"),
      "@mosaix/orchestration": path.resolve(__dirname, "./packages/orchestration/src/index.ts"),
      "@mosaix/ports-database": path.resolve(__dirname, "./packages/ports/database/src/index.ts"),
      "@mosaix/ports-email": path.resolve(__dirname, "./packages/ports/email/src/index.ts"),
      "@mosaix/ports-sms": path.resolve(__dirname, "./packages/ports/sms/src/index.ts"),
      "@mosaix/ports-storage": path.resolve(__dirname, "./packages/ports/storage/src/index.ts"),
      "@mosaix/ports-token-store": path.resolve(__dirname, "./packages/ports/token-store/src/index.ts"),
      "@mosaix/ports-tracing": path.resolve(__dirname, "./packages/ports/tracing/src/index.ts"),
      "@apps/citadelle": path.resolve(__dirname, "./apps/citadelle/src/index.ts"),
      "@apps/commerce": path.resolve(__dirname, "./apps/commerce/src/index.ts"),
      "@apps/spaces": path.resolve(__dirname, "./apps/spaces/src/index.ts"),
      "@apps/imperia": path.resolve(__dirname, "./apps/imperia/src/index.ts"),
      "@apps/solara": path.resolve(__dirname, "./apps/solara/src/index.ts"),
      "@apps/solidarity": path.resolve(__dirname, "./apps/solidarity/src/index.ts"),
      "@apps/beam": path.resolve(__dirname, "./apps/beam/src/index.ts"),
      "@apps/portfolio": path.resolve(__dirname, "./apps/portfolio/src/index.ts"),
      "@apps/booking": path.resolve(__dirname, "./apps/booking/src/index.ts"),
      "@apps/subscription": path.resolve(__dirname, "./apps/subscription/src/index.ts"),
      "@mosaix/dev-session": path.resolve(__dirname, "./packages/dev-session/src/index.ts"),
      "@mosaix/dev-server": path.resolve(__dirname, "./packages/dev-server/src/index.ts"),
    },
  },
});
