/**
 * @apps/solara/plugins — Social Auto-Share Plugin
 * FEAT-08: Partage auto réseaux sociaux [PLUGIN application] (solara + portfolio)
 */

import * as crypto from "node:crypto";
import type { SolaraSocialService } from "./social.model.js";

export type SocialNetworkChannel = "solara" | "x_twitter" | "instagram" | "facebook" | "linkedin";

export interface SocialShareDraft {
  id: string;
  vendableId: string;
  vendableTitle: string;
  vendablePrice: number;
  currency: string;
  vendableUrl: string;
  vendorId: string;
  spaceId?: string;
  suggestedCopy: string;
  selectedChannels: SocialNetworkChannel[];
  status: "draft_pending_review" | "approved_and_published" | "discarded";
  publishedAt?: string;
  createdAt: string;
}

export interface SocialAutoShareSettings {
  autoGenerateDrafts: boolean;
  defaultChannels: SocialNetworkChannel[];
  includePrice: boolean;
  includeHashtags: boolean;
  customHashtags: string[];
}

export class SocialAutoSharePlugin {
  private activeDrafts = new Map<string, SocialShareDraft>();
  private settingsPerSpace = new Map<string, SocialAutoShareSettings>();

  private defaultSettings: SocialAutoShareSettings = {
    autoGenerateDrafts: true,
    defaultChannels: ["solara", "x_twitter"],
    includePrice: true,
    includeHashtags: true,
    customHashtags: ["#Nouveaute", "#Boutique", "#MosaiX"],
  };

  getSettings(spaceId?: string): SocialAutoShareSettings {
    if (spaceId && this.settingsPerSpace.has(spaceId)) {
      return { ...this.settingsPerSpace.get(spaceId)! };
    }
    return { ...this.defaultSettings };
  }

  updateSettings(spaceId: string, settings: Partial<SocialAutoShareSettings>): SocialAutoShareSettings {
    const current = this.getSettings(spaceId);
    const updated = { ...current, ...settings };
    this.settingsPerSpace.set(spaceId, updated);
    return { ...updated };
  }

  /**
   * Called when event `portfolio.vendable.published` is triggered
   */
  handleVendablePublished(eventPayload: {
    vendableId: string;
    name: string;
    price: number;
    currency: string;
    slug: string;
    vendorId: string;
    spaceId?: string;
    description?: string;
  }): SocialShareDraft | null {
    const settings = this.getSettings(eventPayload.spaceId);
    if (!settings.autoGenerateDrafts) {
      return null;
    }

    const id = `share_draft_${crypto.randomUUID()}`;
    const url = `https://mosaix.local/p/${eventPayload.slug}`;
    const priceText = settings.includePrice ? ` au prix de ${eventPayload.price} ${eventPayload.currency}` : "";
    const tags = settings.includeHashtags ? `\n\n${settings.customHashtags.join(" ")}` : "";

    const suggestedCopy = `✨ Découvrez notre nouvelle création : "${eventPayload.name}"${priceText} !\n👉 Disponible dès maintenant sur notre boutique en ligne : ${url}${tags}`;

    const draft: SocialShareDraft = {
      id,
      vendableId: eventPayload.vendableId,
      vendableTitle: eventPayload.name,
      vendablePrice: eventPayload.price,
      currency: eventPayload.currency,
      vendableUrl: url,
      vendorId: eventPayload.vendorId,
      spaceId: eventPayload.spaceId,
      suggestedCopy,
      selectedChannels: [...settings.defaultChannels],
      status: "draft_pending_review",
      createdAt: new Date().toISOString(),
    };

    this.activeDrafts.set(id, draft);
    return draft;
  }

  getDraft(draftId: string): SocialShareDraft | null {
    const draft = this.activeDrafts.get(draftId);
    return draft ? { ...draft } : null;
  }

  listDrafts(filter?: { vendorId?: string; spaceId?: string; status?: string }): SocialShareDraft[] {
    return Array.from(this.activeDrafts.values()).filter((d) => {
      if (filter?.vendorId && d.vendorId !== filter.vendorId) return false;
      if (filter?.spaceId && d.spaceId !== filter.spaceId) return false;
      if (filter?.status && d.status !== filter.status) return false;
      return true;
    });
  }

  /**
   * Seller validates the draft, edits copy if desired, selects final channels, and sends
   */
  async approveAndPublish(
    draftId: string,
    params: {
      finalCopy?: string;
      channels?: SocialNetworkChannel[];
    },
    solaraService?: SolaraSocialService
  ): Promise<SocialShareDraft> {
    const draft = this.activeDrafts.get(draftId);
    if (!draft) {
      throw new Error("Brouillon de partage social introuvable.");
    }

    if (params.finalCopy) {
      draft.suggestedCopy = params.finalCopy;
    }
    if (params.channels && params.channels.length > 0) {
      draft.selectedChannels = params.channels;
    }

    draft.status = "approved_and_published";
    draft.publishedAt = new Date().toISOString();

    // If Solara channel selected and service is provided, publish post in Solara feed
    if (draft.selectedChannels.includes("solara") && solaraService) {
      await solaraService.createPost(
        "space",
        draft.spaceId || draft.vendorId,
        "feed",
        "global",
        draft.suggestedCopy,
        "text",
        { vendableId: draft.vendableId, autoShared: true }
      );
    }

    return { ...draft };
  }

  discardDraft(draftId: string): void {
    const draft = this.activeDrafts.get(draftId);
    if (draft) {
      draft.status = "discarded";
    }
  }
}

export const socialAutoSharePlugin = new SocialAutoSharePlugin();
