/**
 * Autogenerated / Managed BAC Registry.
 * Delegates to DynamicBacRegistry for pluggable and runtime dynamic discovery.
 */
import {
  DynamicBacRegistry,
  type BacPluginRegistration,
} from "./shell/dynamic-bac-registry.js";

export { DynamicBacRegistry, type BacPluginRegistration };
// NOTE (D-01): no frozen bacRegistry snapshot here on purpose — call
// DynamicBacRegistry.getAll() at the usage site so late plugin
// registrations are visible.
