/**
 * Autogenerated / Managed BAC Registry.
 * Delegates to DynamicBacRegistry for pluggable and runtime dynamic discovery.
 */
import { DynamicBacRegistry, type BacPluginRegistration } from "./shell/dynamic-bac-registry.js";

export { DynamicBacRegistry, type BacPluginRegistration };
export const bacRegistry = DynamicBacRegistry.getAll();
